import { Roboto } from 'next/font/google'
import './globals.css'
import Link from "next/link"

const inter = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Woo App by Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='m-2 bg-slate-600'>
          <ul className="flex gap-6">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/blog">Blog</Link></li>
            <li><Link href="/post">Post</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
