export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="m-2 bg-teal-900 h-screen">
      Home
    </main>
  )
}
